- .github/workflows/aws-ci-synth.yml
This makes CI checks faster.
It leverages:
- cache to skip install step when lockfile did not change
- parallelisation of checks (`tsc`, `lint`, `unit tests`, `cdk synth`)
Reduces worflow from 9m27 to 7m46 (and sometimes to 4m19)
> feat: optimize CI checks

- .github/workflows/aws-ci-synth.yml
> chore: short lived cache key

- .github/workflows/aws-ci-synth.yml
This adds a sast check in the synth workflow
> feat: add sast check in ci

- .github/workflows/aws-ci-synth.yml
> ci: Update aws-ci-synth.yml

- .github/workflows/cherry-pick.yml
> feat: Add cherry-pick workflow

- .github/workflows/deploy-bundle.yml
> fix: Add env to the S3 path in deploy-bundle workflow

- .github/workflows/build-upload-bundle.yml
This is needed if we want to let the Webapp repo use this workflow since it's architecture is not compatible with the default value.
> chore(build-upload-bundle): Parametrize working directory

- .github/workflows/deploy-bundle.yml
> chore: Notify in case of bundling failure

- .github/workflows/lokalise-pull.yml
> ci: Update lokalise-pull.yml

- .github/workflows/build-upload-bundle.yml
> chore: Add success file to build-upload-bundle

- .github/workflows/build-upload-bundle.yml
> chore(build-upload-bundle): Remove ref, use tag-version instead

- .github/workflows/aws-ci-synth.yml
Fixes final step for dependabot case
> fix: error only on failure

- .github/workflows/build-upload-bundle.yml
> fix(build-upload-bundle): Add env to success file path

- .github/workflows/build-upload-bundle.yml
- .github/workflows/npm-package-release.yml
> ci: deploy bundle after tagging

- .github/workflows/api-upgrade.yml
> fix(api-upgrade): Inputs references

- .github/workflows/api-upgrade.yml
> chore(api-upgrade): Add log + properly retrieve version

- .github/workflows/build-upload-bundle.yml
The step to properly set the Slack Webhook secret was skipped in case of failure but we want to notify slack in that specific case.
> fix(build-upload-bundle): Properly set Slack Webhook secret

- .github/workflows/build-upload-bundle.yml
We don't use bundles for dev environment so let's remove it to save some GHA credits
> chore(build-upload-bundle): Remove dev environment

- .github/workflows/api-upgrade.yml
> chore(api-upgrade): Retrieve version from package.json

- .github/workflows/npm-package-release.yml
Needed to let the workflow trigger another workflow
> fix(npm-package-release): Add action: write permission

- .github/workflows/build-upload-bundle.yml
> chore(build-upload-bundle): Remove unused SLACK_WEBHOOK secret

- .github/workflows/api-upgrade.yml
> chore(api-upgrade): Add workspace input

- .github/workflows/cherry-pick.yml
> chore(cherry-pick): Mention PR author on conflicts

- .github/workflows/api-upgrade.yml
> fix(api-upgrade): Invalid variable name

- .github/workflows/npm-package-release-and-bundling.yml
This workflow will call the npm-package-release reusable workflow to release an API and trigger the build-upload-bundle workflow on the target repo.
> feat: Add npm-package-release-and-bundling

- .github/workflows/npm-package-release-and-bundling.yml
- .github/workflows/npm-package-release.yml
This is done mainly to ensure there was a diff indeed.
> chore(npm-package-release-and-bundling): Use release-api outputs in trigger-bundling

- .github/workflows/npm-package-release-and-bundling.yml
> fix(npm-package-release-and-bundling): Add content: read permission

- .github/workflows/npm-package-release-and-bundling.yml
> fix(npm-package-release-and-bundling): Add content: write permission

- .github/workflows/api-upgrade.yml
Necessary to check private dependencies
> fix(api-upgrade): Add Github Token secret

- .github/workflows/build-upload-bundle.yml
> fix(build-upload-bundle): Add slack webhook secrets

- .github/workflows/api-upgrade.yml
> chore(api-upgrade): Remove silent option from npm version to get logs

- .github/workflows/api-upgrade.yml
> fix(api-upgrade): Add package:read permission

- .github/workflows/api-upgrade.yml
> chore(api-upgrade): Upgrade only if package-lock.json has changed

- .github/workflows/api-upgrade.yml
> fix(api-upgrade): Use workspace input to construct tag

- .github/workflows/api-upgrade.yml
Prefixes the PR title with a distinctive tag so [Nautilus can automerge it](https://github.com/Bastion-Technologies/nautilus/pull/387)
> chore(api-upgrade): Change PR title

- .github/workflows/api-upgrade.yml
This will allow the automatic API upgrade PRs to run the CI checks.
Also changing the PR Title format to pass Lint PR check.
> ci(api-upgrade): Open PR with Nautilus

- .github/workflows/api-upgrade.yml
> chore(api-upgrade): Add nautilus secret

- .github/workflows/api-upgrade.yml
> fix(api-upgrade): Add expected secrets inputs

- .github/workflows/lokalise-pull.yml
when status is not 2xx we should fail
> ci: lokalise pull should fail properly

- .github/workflows/api-upgrade.yml
> fix(api-upgrade): Git config author identity

- .github/workflows/lokalise-pull.yml
> fix: Update lokalise-pull.yml

- .github/workflows/nautilus-pr.yml
> ci: Create nautilus-pr.yml reusable workflow

- .github/workflows/api-upgrade.yml
> fix(api-upgrade): Dash between api and version only if api exists

- .github/workflows/api-upgrade.yml
The `upgrade:api` script can be pretty different from one repo to the other so it's better to use directly the `npm version` command instead to ensure consistent behavior across all repos.
> chore(api-upgrade): Do not use npm script to upgrade

- .github/workflows/update-bt-dependencies.yml
> fix: update-bt-dependencies workflow

- .github/workflows/package-version-changed.yml
- Early return if no breaking change is found
- Ignore `grep` exit code as it returns `1` if no result is found, using `|| true`
> fix(package-version-changed): Breaking change check error handling

- .github/workflows/package-version-changed.yml
And ignore sunset-related errors
> fix(package-version-changed): Allow to ignore multiple breaking-changes

- .github/workflows/package-version-changed.yml
> fix(package-version-changed): Breaking change exit 0 if no breaking change after filtering

- .github/workflows/aws-ci-synth.yml
> fix(aws-ci-synth): Add output to has-cdk-changed

- .github/workflows/nautilus-merge.yml
Allows to call Nautilus to merge a Pull Request
> feat: Add nautilus-merge workflow

- .github/workflows/nautilus-merge.yml
> fix(nautilus-merge): Make inputs with default optional

- .github/workflows/api-upgrade.yml
> fix(api-upgrade): Git auth before npm version

- .github/workflows/api-upgrade.yml
> fix(api-upgrade): use --no-git-tag-version

- .github/workflows/aws-ci-v2.yml
> fix(aws-ci-v2): Slack channel

- .github/workflows/package-version-changed.yml
> fix(check-api-breaking-change): Should exit 0 if there is no breaking change after filtering

- .github/workflows/check-unused-dependencies.yml
> feat: Add check-unused-dependencies workflow

- .github/workflows/check-unused-dependencies.yml
This has 2 effects
- Avoids a non-zero exit code if there is no workspace, breaking the workflow
- Simplify getting the root workspace path
> fix(check-unused-dependencies): Use --include-workspace-root

- .github/workflows/check-unused-dependencies.yml
> fix(check-unused-dependencies): properly ignore workspaces

- .github/workflows/check-unused-dependencies.yml
> fix(check-unused-dependencies): Echo newline

- .github/workflows/check-adr.yml
This workflow will check for the presence of a new ADR document in Pull Requests.
It can by bypassed by checking a checkbox in the PR Description to notify that this specific PR doesn't need an ADR.
> feat: Create check-adr workflow

- .github/workflows/lokalise-pull.yml
> fix(lokalise-pull): Accept schedule event types

- .github/workflows/lint-pr.yml
> ci(lint-pr): Add ADR check

- .github/workflows/update-bt-dependencies.yml
We were previously checking if the actor was dependabot However, if someone else merges a Dependabot PR, the actor will not be dependabot and this workflow will not be triggered.
Instead, we now check that the branch contains `dependabot`
> fix(update-bt-dependencies): run condition

- .github/workflows/check-adr.yml
- .github/workflows/check-unused-dependencies.yml
`check-unused-dependencies` and `check-adr` should not be run in Dependabot PRs.
> chore: Skip some workflows in Dependabot PRs

- .github/workflows/lint-pr.yml
> chore(lint-pr): explicit permissions

- .github/workflows/aws-ci-synth.yml
> feat(aws-ci-synth): Implement NX testing

- .github/workflows/api-upgrade.yml
Use a github action to auto approve instead of delegating to Nautilus, which obviously doesn't work since Nautilus is also the PR author and can't approve its own PR.
> fix(api-upgrade): Auto approve action

- .github/workflows/check-adr.yml
> fix(check-adr): use head_ref in diff

- .github/workflows/check-adr.yml
> chore(check-adr): Skip lokalise PRs

- .github/workflows/aws-ci-synth.yml
- .github/workflows/aws-ci-v2.yml
- .github/workflows/aws-ci.yml
- .github/workflows/build-upload-bundle.yml
- .github/workflows/check-unused-dependencies.yml
- .github/workflows/npm-package-release.yml
- .github/workflows/package-version-changed.yml
- .github/workflows/sast.yml
Seems like there is some issues with 18.19.1 so let's try keeping
the previous version.
Also update checkout and setup node action version.
> chore: Pin node version to 18.19.0 

- .github/workflows/api-upgrade.yml
> fix(api-upgrade): Correctly retrieve PR number in auto approve step

- .github/workflows/check-adr.yml
> chore(check-adr): Ignore nautilus PRs

- .github/workflows/api-upgrade.yml
> fix(api-upgrade): Exit 1 when git diff has an error (code 128)

- .github/workflows/aws-ci-synth.yml
- Ensure caching is always done, even in case of failure
- Ensure only the same workspace can retrieve its cache
> chore(aws-ci-synth): Fine-tune NX cache

- .github/workflows/check-unused-dependencies.yml
> fix(check-unused-dependencies): Set working dir to cdk when installing dependencies

- .github/workflows/aws-ci-synth.yml
- .github/workflows/check-unused-dependencies.yml
Remove the `working-directory` configuration from `aws-ci-synth` and `check-unused-dependencies` workflow to be able to run them on repos without a cdk folder.
> chore: remove cdk folder dependency

- .github/workflows/aws-ci.yml
> fix(aws-ci): Set default directory to cdk

- .github/workflows/aws-ci-synth.yml
> ci(aws-ci-synth): Enable checks for Dependabot

- .github/workflows/aws-ci-synth.yml
> fix(aws-ci-synth): Enable build for dependabot

- .github/workflows/aws-ci-synth.yml
> chore(aws-ci-synth): Add manta verify step

- .github/workflows/aws-ci-synth.yml
- .github/workflows/aws-ci-v2.yml
- .github/workflows/check-unused-dependencies.yml
> chore: cancel previous workflow when a new one is triggered

- .github/workflows/aws-ci.yml
> chore: set aws-ci concurrency

- .github/workflows/check-unused-dependencies.yml
Ignore esbuild in the list of unused dependencies.
> feat: ignore esbuild in unused dependencies

- .github/workflows/aws-ci-synth.yml
- .github/workflows/check-adr.yml
- .github/workflows/check-unused-dependencies.yml
- .github/workflows/lint-pr.yml
> chore: disable checks for weblate

- .github/workflows/check-translations.yml
Adds non-blocking CI check for
- Missing translations (keys present in the source lang and not in a target lang)
- Outdated translations (keys present in a target lang and not in the source lang)
This will post comments on the PR listing the potential errors (see here for an example: https://github.com/Bastion-Technologies/webapp/pull/4374)
> feat: add check-translations workflow

- .github/workflows/aws-ci-synth.yml
Fix a edge case where there is no workspace. In that case we should fully skip the tests or the Final Step will `exit 1`.
This will allow to use this workflow for `cdk-common`
> fix(aws-ci-synth): no workspace case

- .github/workflows/aws-ci-v2.yml
- .github/workflows/aws-ci.yml
- .github/workflows/build-upload-bundle.yml
> chore: migrate sensitive workflows to self-hosted

- .github/workflows/aws-ci-synth.yml
> feat(aws-ci-synth): dynamic runner

- .github/workflows/sast.yml
> ci: change sast to use custom action

- .github/workflows/aws-ci-synth.yml
> chore: update to v4

- .github/workflows/aws-ci-synth.yml
- .github/workflows/aws-ci-v2.yml
- .github/workflows/aws-ci.yml
- .github/workflows/build-upload-bundle.yml
- .github/workflows/check-unused-dependencies.yml
- .github/workflows/npm-package-release.yml
- .github/workflows/package-version-changed.yml
Update to current node LTS version: 22.11.0
> chore: update node LTS

- .github/workflows/api-upgrade.yml
- .github/workflows/aws-ci-self-hosted-tests.yml
- .github/workflows/aws-ci-v2.yml
- .github/workflows/build-upload-bundle.yml
- .github/workflows/cherry-pick.yml
- .github/workflows/sast.yml
> chore: update actions versions

- .github/workflows/aws-ci-synth.yml
Cache installed modules under the cache key which is hash of the package lock. In case no exact match is found take any cached installed modules
> ci: enable npm i cache

- .github/workflows/api-upgrade.yml
> fix(api-upgrade): Run if the tag isn't found

- .github/workflows/build-upload-bundle.yml
This will allow the build script to retrieve and use the release version.
Linked to https://github.com/Bastion-Technologies/webapp/pull/5051
> chore(build-upload-bundle): sets BASTION_RELEASE_VERSION env variable

- .github/workflows/build-upload-bundle.yml
> ci: use LFS (optional)

- .github/workflows/api-upgrade.yml
- .github/workflows/aws-ci-synth.yml
- .github/workflows/check-adr.yml
- .github/workflows/check-translations.yml
- .github/workflows/check-unused-dependencies.yml
- .github/workflows/cherry-pick.yml
- .github/workflows/dependabot.yml
- .github/workflows/lint-pr.yml
- .github/workflows/nautilus-merge.yml
- .github/workflows/npm-package-release-and-bundling.yml
- .github/workflows/npm-package-release.yml
- .github/workflows/package-version-changed.yml
- .github/workflows/sast.yml
- .github/workflows/update-bt-dependencies.yml
> fix: temporarily pin ubuntu version

- .github/workflows/aws-ci-synth.yml
> ci: add setup node

- .github/workflows/check-pr-labels.yml
> fix(check-pr-labels): handle do not merge label

- .github/workflows/check-pr-labels.yml
> fix: check-pr-labels

- .github/workflows/check-pr-labels.yml
> fix: use simple quotes in check-pr-labels

- .github/workflows/package-version-changed.yml
> ci: prevent bash injections

- .github/workflows/api-upgrade-pnpm.yml
- .github/workflows/check-unused-dependencies-pnpm.yml
- .github/workflows/package-version-changed-pnpm.yml
- .github/workflows/pnpm-package-release.yml
- .github/workflows/update-bt-dependencies-pnpm.yml
> fix: install pnpm in pnpm workflows

- .github/workflows/check-unused-dependencies-pnpm.yml
> fix(check-unused-dependencies-pnpm): workspaces retrieval

- .github/workflows/lint-pr.yml
> fix: remove adr check

- .github/workflows/pnpm-package-release.yml
> fix(pnpm-package-release): remove useless cache

- .github/workflows/check-unused-dependencies-pnpm.yml
- .github/workflows/check-unused-dependencies.yml
> chore(check-unused-dependencies): cache node modules
